/**
 * Top 100 Cryptocurrencies - Static Data
 * Logos from CoinGecko CDN
 */

const TOP_100_COINS = [
    { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin', image: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png' },
    { id: 'ethereum', symbol: 'ETH', name: 'Ethereum', image: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png' },
    { id: 'tether', symbol: 'USDT', name: 'Tether', image: 'https://assets.coingecko.com/coins/images/325/small/Tether.png' },
    { id: 'binancecoin', symbol: 'BNB', name: 'BNB', image: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png' },
    { id: 'solana', symbol: 'SOL', name: 'Solana', image: 'https://assets.coingecko.com/coins/images/4128/small/solana.png' },
    { id: 'usd-coin', symbol: 'USDC', name: 'USD Coin', image: 'https://assets.coingecko.com/coins/images/6319/small/usdc.png' },
    { id: 'ripple', symbol: 'XRP', name: 'XRP', image: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png' },
    { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin', image: 'https://assets.coingecko.com/coins/images/5/small/dogecoin.png' },
    { id: 'cardano', symbol: 'ADA', name: 'Cardano', image: 'https://assets.coingecko.com/coins/images/975/small/cardano.png' },
    { id: 'staked-ether', symbol: 'STETH', name: 'Lido Staked Ether', image: 'https://assets.coingecko.com/coins/images/13442/small/steth_logo.png' },
    { id: 'tron', symbol: 'TRX', name: 'TRON', image: 'https://assets.coingecko.com/coins/images/1094/small/tron-logo.png' },
    { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche', image: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png' },
    { id: 'chainlink', symbol: 'LINK', name: 'Chainlink', image: 'https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png' },
    { id: 'wrapped-bitcoin', symbol: 'WBTC', name: 'Wrapped Bitcoin', image: 'https://assets.coingecko.com/coins/images/7598/small/wrapped_bitcoin_wbtc.png' },
    { id: 'sui', symbol: 'SUI', name: 'Sui', image: 'https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg' },
    { id: 'shiba-inu', symbol: 'SHIB', name: 'Shiba Inu', image: 'https://assets.coingecko.com/coins/images/11939/small/shiba.png' },
    { id: 'polkadot', symbol: 'DOT', name: 'Polkadot', image: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png' },
    { id: 'bitcoin-cash', symbol: 'BCH', name: 'Bitcoin Cash', image: 'https://assets.coingecko.com/coins/images/780/small/bitcoin-cash-circle.png' },
    { id: 'hyperliquid', symbol: 'HYPE', name: 'Hyperliquid', image: 'https://assets.coingecko.com/coins/images/40488/small/hyperliquid.jpeg' },
    { id: 'stellar', symbol: 'XLM', name: 'Stellar', image: 'https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png' },
    { id: 'uniswap', symbol: 'UNI', name: 'Uniswap', image: 'https://assets.coingecko.com/coins/images/12504/small/uniswap-logo.png' },
    { id: 'hedera-hashgraph', symbol: 'HBAR', name: 'Hedera', image: 'https://assets.coingecko.com/coins/images/3688/small/hbar.png' },
    { id: 'litecoin', symbol: 'LTC', name: 'Litecoin', image: 'https://assets.coingecko.com/coins/images/2/small/litecoin.png' },
    { id: 'pepe', symbol: 'PEPE', name: 'Pepe', image: 'https://assets.coingecko.com/coins/images/29850/small/pepe-token.jpeg' },
    { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol', image: 'https://assets.coingecko.com/coins/images/10365/small/near.jpg' },
    { id: 'dai', symbol: 'DAI', name: 'Dai', image: 'https://assets.coingecko.com/coins/images/9956/small/Badge_Dai.png' },
    { id: 'internet-computer', symbol: 'ICP', name: 'Internet Computer', image: 'https://assets.coingecko.com/coins/images/14495/small/Internet_Computer_logo.png' },
    { id: 'aptos', symbol: 'APT', name: 'Aptos', image: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png' },
    { id: 'ethereum-classic', symbol: 'ETC', name: 'Ethereum Classic', image: 'https://assets.coingecko.com/coins/images/453/small/ethereum-classic-logo.png' },
    { id: 'crypto-com-chain', symbol: 'CRO', name: 'Cronos', image: 'https://assets.coingecko.com/coins/images/7310/small/cro_token_logo.png' },
    { id: 'render-token', symbol: 'RNDR', name: 'Render', image: 'https://assets.coingecko.com/coins/images/11636/small/rndr.png' },
    { id: 'kaspa', symbol: 'KAS', name: 'Kaspa', image: 'https://assets.coingecko.com/coins/images/25751/small/kaspa-icon-exchanges.png' },
    { id: 'polygon-ecosystem-token', symbol: 'POL', name: 'Polygon', image: 'https://assets.coingecko.com/coins/images/32440/small/polygon.png' },
    { id: 'aave', symbol: 'AAVE', name: 'Aave', image: 'https://assets.coingecko.com/coins/images/12645/small/AAVE.png' },
    { id: 'artificial-superintelligence-alliance', symbol: 'FET', name: 'Fetch.ai', image: 'https://assets.coingecko.com/coins/images/5681/small/Fetch.jpg' },
    { id: 'vechain', symbol: 'VET', name: 'VeChain', image: 'https://assets.coingecko.com/coins/images/1167/small/VET_Token_Icon.png' },
    { id: 'monero', symbol: 'XMR', name: 'Monero', image: 'https://assets.coingecko.com/coins/images/69/small/monero_logo.png' },
    { id: 'virtual-protocol', symbol: 'VIRTUAL', name: 'Virtuals Protocol', image: 'https://assets.coingecko.com/coins/images/36285/small/Virtuals.jpeg' },
    { id: 'mantra-dao', symbol: 'OM', name: 'MANTRA', image: 'https://assets.coingecko.com/coins/images/12151/small/OM_3D_whtbg.png' },
    { id: 'bonk', symbol: 'BONK', name: 'Bonk', image: 'https://assets.coingecko.com/coins/images/28600/small/bonk.jpg' },
    { id: 'okb', symbol: 'OKB', name: 'OKB', image: 'https://assets.coingecko.com/coins/images/4463/small/WeChat_Image_20220118095654.png' },
    { id: 'injective-protocol', symbol: 'INJ', name: 'Injective', image: 'https://assets.coingecko.com/coins/images/12882/small/Secondary_Symbol.png' },
    { id: 'bittensor', symbol: 'TAO', name: 'Bittensor', image: 'https://assets.coingecko.com/coins/images/28452/small/ARUsPeNQ_400x400.jpeg' },
    { id: 'filecoin', symbol: 'FIL', name: 'Filecoin', image: 'https://assets.coingecko.com/coins/images/12817/small/filecoin.png' },
    { id: 'cosmos', symbol: 'ATOM', name: 'Cosmos', image: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png' },
    { id: 'immutable-x', symbol: 'IMX', name: 'Immutable', image: 'https://assets.coingecko.com/coins/images/17233/small/immutableX-symbol-BLK-RGB.png' },
    { id: 'theta-token', symbol: 'THETA', name: 'Theta Network', image: 'https://assets.coingecko.com/coins/images/2538/small/theta-token-logo.png' },
    { id: 'celestia', symbol: 'TIA', name: 'Celestia', image: 'https://assets.coingecko.com/coins/images/31967/small/tia.jpg' },
    { id: 'fantom', symbol: 'FTM', name: 'Fantom', image: 'https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png' },
    { id: 'first-digital-usd', symbol: 'FDUSD', name: 'First Digital USD', image: 'https://assets.coingecko.com/coins/images/31079/small/firstdigitalusd.jpeg' },
    { id: 'algorand', symbol: 'ALGO', name: 'Algorand', image: 'https://assets.coingecko.com/coins/images/4380/small/download.png' },
    { id: 'optimism', symbol: 'OP', name: 'Optimism', image: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png' },
    { id: 'sei-network', symbol: 'SEI', name: 'Sei', image: 'https://assets.coingecko.com/coins/images/28205/small/Sei_Logo_-_Transparent.png' },
    { id: 'the-graph', symbol: 'GRT', name: 'The Graph', image: 'https://assets.coingecko.com/coins/images/13397/small/Graph_Token.png' },
    { id: 'maker', symbol: 'MKR', name: 'Maker', image: 'https://assets.coingecko.com/coins/images/1364/small/Mark_Maker.png' },
    { id: 'ondo-finance', symbol: 'ONDO', name: 'Ondo', image: 'https://assets.coingecko.com/coins/images/26580/small/ONDO.png' },
    { id: 'arbitrum', symbol: 'ARB', name: 'Arbitrum', image: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg' },
    { id: 'jupiter-exchange-solana', symbol: 'JUP', name: 'Jupiter', image: 'https://assets.coingecko.com/coins/images/34188/small/jup.png' },
    { id: 'worldcoin-wld', symbol: 'WLD', name: 'Worldcoin', image: 'https://assets.coingecko.com/coins/images/31069/small/worldcoin.jpeg' },
    { id: 'floki', symbol: 'FLOKI', name: 'FLOKI', image: 'https://assets.coingecko.com/coins/images/16746/small/PNG_image.png' },
    { id: 'lido-dao', symbol: 'LDO', name: 'Lido DAO', image: 'https://assets.coingecko.com/coins/images/13573/small/Lido_DAO.png' },
    { id: 'pyth-network', symbol: 'PYTH', name: 'Pyth Network', image: 'https://assets.coingecko.com/coins/images/31924/small/pyth.png' },
    { id: 'gala', symbol: 'GALA', name: 'Gala', image: 'https://assets.coingecko.com/coins/images/12493/small/GALA-COINGECKO.png' },
    { id: 'the-sandbox', symbol: 'SAND', name: 'The Sandbox', image: 'https://assets.coingecko.com/coins/images/12129/small/sandbox_logo.jpg' },
    { id: 'flow', symbol: 'FLOW', name: 'Flow', image: 'https://assets.coingecko.com/coins/images/13446/small/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png' },
    { id: 'aioz-network', symbol: 'AIOZ', name: 'AIOZ Network', image: 'https://assets.coingecko.com/coins/images/14631/small/aioz_logo.png' },
    { id: 'kucoin-shares', symbol: 'KCS', name: 'KuCoin Token', image: 'https://assets.coingecko.com/coins/images/1047/small/sa9z79.png' },
    { id: 'quant-network', symbol: 'QNT', name: 'Quant', image: 'https://assets.coingecko.com/coins/images/3370/small/5ZOu7brX_400x400.jpg' },
    { id: 'beam-2', symbol: 'BEAM', name: 'Beam', image: 'https://assets.coingecko.com/coins/images/32417/small/chain-logo.png' },
    { id: 'eos', symbol: 'EOS', name: 'EOS', image: 'https://assets.coingecko.com/coins/images/738/small/eos-eos-logo.png' },
    { id: 'raydium', symbol: 'RAY', name: 'Raydium', image: 'https://assets.coingecko.com/coins/images/13928/small/PSigc4ie_400x400.jpg' },
    { id: 'tezos', symbol: 'XTZ', name: 'Tezos', image: 'https://assets.coingecko.com/coins/images/976/small/Tezos-logo.png' },
    { id: 'axie-infinity', symbol: 'AXS', name: 'Axie Infinity', image: 'https://assets.coingecko.com/coins/images/13029/small/axie_infinity_logo.png' },
    { id: 'brett', symbol: 'BRETT', name: 'Brett', image: 'https://assets.coingecko.com/coins/images/35529/small/brett-logo.png' },
    { id: 'iota', symbol: 'IOTA', name: 'IOTA', image: 'https://assets.coingecko.com/coins/images/692/small/IOTA_Swirl.png' },
    { id: 'neo', symbol: 'NEO', name: 'Neo', image: 'https://assets.coingecko.com/coins/images/480/small/NEO_512_512.png' },
    { id: 'stacks', symbol: 'STX', name: 'Stacks', image: 'https://assets.coingecko.com/coins/images/2069/small/Stacks_logo_full.png' },
    { id: 'core', symbol: 'CORE', name: 'Core', image: 'https://assets.coingecko.com/coins/images/28938/small/file_589.jpg' },
    { id: 'decentraland', symbol: 'MANA', name: 'Decentraland', image: 'https://assets.coingecko.com/coins/images/878/small/decentraland-mana.png' },
    { id: 'helium', symbol: 'HNT', name: 'Helium', image: 'https://assets.coingecko.com/coins/images/4284/small/Helium_HNT.png' },
    { id: 'bitget-token', symbol: 'BGB', name: 'Bitget Token', image: 'https://assets.coingecko.com/coins/images/11610/small/icon_colour.png' },
    { id: 'arweave', symbol: 'AR', name: 'Arweave', image: 'https://assets.coingecko.com/coins/images/4343/small/oRt6SiEN_400x400.jpg' },
    { id: 'ethena', symbol: 'ENA', name: 'Ethena', image: 'https://assets.coingecko.com/coins/images/36530/small/ethena.png' },
    { id: 'kaia', symbol: 'KAIA', name: 'Kaia', image: 'https://assets.coingecko.com/coins/images/39875/small/kaia.png' },
    { id: 'curve-dao-token', symbol: 'CRV', name: 'Curve DAO', image: 'https://assets.coingecko.com/coins/images/12124/small/Curve.png' },
    { id: 'jito-governance-token', symbol: 'JTO', name: 'Jito', image: 'https://assets.coingecko.com/coins/images/33228/small/jto.png' },
    { id: 'usdd', symbol: 'USDD', name: 'USDD', image: 'https://assets.coingecko.com/coins/images/25380/small/USDD.jpg' },
    { id: 'jasmy', symbol: 'JASMY', name: 'JasmyCoin', image: 'https://assets.coingecko.com/coins/images/13876/small/JASMY200x200.jpg' },
    { id: 'chiliz', symbol: 'CHZ', name: 'Chiliz', image: 'https://assets.coingecko.com/coins/images/8834/small/CHZ_Token_updated.png' },
    { id: 'mantle', symbol: 'MNT', name: 'Mantle', image: 'https://assets.coingecko.com/coins/images/30980/small/token-logo.png' },
    { id: 'pendle', symbol: 'PENDLE', name: 'Pendle', image: 'https://assets.coingecko.com/coins/images/15069/small/Pendle_Logo_Normal-03.png' },
    { id: 'dydx-chain', symbol: 'DYDX', name: 'dYdX', image: 'https://assets.coingecko.com/coins/images/32594/small/dydx.png' },
    { id: 'dogwifcoin', symbol: 'WIF', name: 'dogwifhat', image: 'https://assets.coingecko.com/coins/images/33566/small/dogwifhat.jpg' },
    { id: 'tokenize-xchange', symbol: 'TKX', name: 'Tokenize Xchange', image: 'https://assets.coingecko.com/coins/images/4984/small/TKX_-_Logo_-_RGB-15.png' },
    { id: 'xdc-network', symbol: 'XDC', name: 'XDC Network', image: 'https://assets.coingecko.com/coins/images/2912/small/xdc-icon.png' },
    { id: 'wormhole', symbol: 'W', name: 'Wormhole', image: 'https://assets.coingecko.com/coins/images/35087/small/wormhole_logo.png' },
    { id: 'zcash', symbol: 'ZEC', name: 'Zcash', image: 'https://assets.coingecko.com/coins/images/486/small/circle-zcash-color.png' },
    { id: 'thorchain', symbol: 'RUNE', name: 'THORChain', image: 'https://assets.coingecko.com/coins/images/6595/small/Rune200x200.png' },
    { id: 'notcoin', symbol: 'NOT', name: 'Notcoin', image: 'https://assets.coingecko.com/coins/images/36667/small/notcoin.png' }
];

// Default segment assignments based on coin type
const DEFAULT_SEGMENTS = {
    'bitcoin': 'store_of_value',
    'wrapped-bitcoin': 'store_of_value',
    'litecoin': 'payments',
    'bitcoin-cash': 'payments',
    'monero': 'payments',
    'zcash': 'payments',
    'stellar': 'payments',
    'ripple': 'payments',
    'dogecoin': 'payments',
    'shiba-inu': 'payments',
    'pepe': 'payments',
    'bonk': 'payments',
    'floki': 'payments',
    'brett': 'payments',
    'dogwifcoin': 'payments',
    'notcoin': 'payments',
    'tether': 'payments',
    'usd-coin': 'payments',
    'dai': 'payments',
    'first-digital-usd': 'payments',
    'usdd': 'payments',
    'ethereum': 'infrastructure',
    'solana': 'infrastructure',
    'cardano': 'infrastructure',
    'avalanche-2': 'infrastructure',
    'polkadot': 'infrastructure',
    'near': 'infrastructure',
    'cosmos': 'infrastructure',
    'tron': 'infrastructure',
    'sui': 'infrastructure',
    'aptos': 'infrastructure',
    'internet-computer': 'infrastructure',
    'ethereum-classic': 'infrastructure',
    'kaspa': 'infrastructure',
    'polygon-ecosystem-token': 'infrastructure',
    'fantom': 'infrastructure',
    'algorand': 'infrastructure',
    'optimism': 'infrastructure',
    'sei-network': 'infrastructure',
    'arbitrum': 'infrastructure',
    'flow': 'infrastructure',
    'eos': 'infrastructure',
    'tezos': 'infrastructure',
    'iota': 'infrastructure',
    'neo': 'infrastructure',
    'stacks': 'infrastructure',
    'core': 'infrastructure',
    'helium': 'infrastructure',
    'kaia': 'infrastructure',
    'mantle': 'infrastructure',
    'xdc-network': 'infrastructure',
    'wormhole': 'infrastructure',
    'hedera-hashgraph': 'infrastructure',
    'celestia': 'infrastructure',
    'staked-ether': 'defi',
    'uniswap': 'defi',
    'aave': 'defi',
    'lido-dao': 'defi',
    'maker': 'defi',
    'curve-dao-token': 'defi',
    'injective-protocol': 'defi',
    'raydium': 'defi',
    'jupiter-exchange-solana': 'defi',
    'pendle': 'defi',
    'dydx-chain': 'defi',
    'jito-governance-token': 'defi',
    'thorchain': 'defi',
    'ethena': 'defi',
    'ondo-finance': 'defi',
    'hyperliquid': 'defi',
    'chainlink': 'real_world',
    'the-graph': 'real_world',
    'filecoin': 'real_world',
    'vechain': 'real_world',
    'theta-token': 'entertainment',
    'pyth-network': 'real_world',
    'quant-network': 'real_world',
    'arweave': 'real_world',
    'aioz-network': 'real_world',
    'jasmy': 'real_world',
    'worldcoin-wld': 'real_world',
    'render-token': 'ai_compute',
    'artificial-superintelligence-alliance': 'ai_compute',
    'bittensor': 'ai_compute',
    'virtual-protocol': 'ai_compute',
    'immutable-x': 'entertainment',
    'gala': 'entertainment',
    'the-sandbox': 'entertainment',
    'axie-infinity': 'entertainment',
    'decentraland': 'entertainment',
    'beam-2': 'entertainment',
    'chiliz': 'entertainment',
    'binancecoin': 'infrastructure',
    'crypto-com-chain': 'infrastructure',
    'okb': 'infrastructure',
    'kucoin-shares': 'infrastructure',
    'bitget-token': 'infrastructure',
    'tokenize-xchange': 'infrastructure',
    'mantra-dao': 'defi'
};
